---
title: "Northwest Atlantic Seabird Catalog Species Codes"
---

Species codes are listed in alphabetical order, and grouped by species type. Generally codes are the first two letters of the first word and first two letters of the second code, however not all codes fit this format. Be aware that some of the unidentified codes do not start with "UN" (e.g. JUNC = Unidentified Junco).  

```{r set-options, echo=FALSE, include=FALSE, message=FALSE, warning=FALSE, error=FALSE, cache=FALSE}

library(knitr)

spp = cbind(c("Birds","","","","","","","","","","","","","","","","","","","","",
              "","","","","","","","","","","","","","","","","","","","",
              "","","","","","","","","","","","","","","","","","","","",
              "","","","","","","","","","","","","","","","","","","","",
              "","","","","","","","","","","","","","","","","","","","",
              "","","","","","","","","","","","","","","","","","","","",
              "","","","","","","","","","","","","","","","","","","","",
              "","","","","","","","","","","","","","","","","","","","",
              "","","","","","","","","","","","","","","","","","","","",
              "","","","","","","","","","","","","","","","","","","","",
              "","","","","","","","","","","","","","","","","","","","",
              "","","","","","","","","","","","","","","","","","","","",
              "","","","","","","","","","","","","","","","","","","","",
              "","","","","","","","","","","","","","","","","","","","",
              "","","","","","","","","","","","","","","","","","","","",
              "","","","","","","","","","","","","","","","","","","","",
              "","","","","","","","","","","","","","","","","","","","",
              "","","","","","","","","","","","","","","","","","","","",
              "","","","","","","","","","","","","","","","","","","","",
              "","","","","","","","","","","","","","","","","","","","",
              "","","","","","","","","","","","","","","","","","","","",
              "","","","","","","","","","","","","","","","","","","","",
              "","","","","","","","","","","","","","","","","","","","",
              "","","","","","","","","","","","","","","","","","","","",
              "","","","","","","","","","","","","","","",
              "Cetacean","","","","","","","","","","","","","","","","","","","",
              "","","","","","","","","","","","","","","","","","","","",
              "","","","","","","","","","","","","","","","","","","","","","","","",
              "Fish","","","","","","","","","","","","","","","","","","","",
              "","","","","","","","","","","","","","","","","","","","",
              "Other","","","","","","","","","","","","","","","","","","","",
              "","","","","","","","","","","","","","","","","","","","",
              "","","","","","","","","","","","","","","","","","","","",
              "","","","","","","","","","","","","","","","","","","",
              "Sea Turtles","","","","","","",""),
            c("ABDH",  "ABDU",  "AMBI",  "AMCO",  "AMCR",  "AMGO",  "AMGP",  "AMKE",  "AMOY",  "AMPI",  
              "AMRE",  "AMRO",  "AMWI", "AMWO",  "ANHI",  "APLO",  "ARLO",  "ARTE",  "ATPU",  "ATSP",  
              "AUSH",  "AWPE",  "BAEA",  "BAGO",  "BANO",  "BANS","BAOR",  "BAOW",  "BARS",  "BASA",  
              "BAWW",  "BBCU",  "BBPL",  "BBSP",  "BBWO",  "BCCH",  "BCNH",  "BCPE",  "BEKI", "BEPE",  
              "BFAL",  "BGGN",  "BHCO",  "BHGU",  "BLBW",  "BLGU",  "BLJA",  "BLKI",  "BLNO",  "BLOY",  
              "BLPW",  "BLSC", "BLSK",  "BLSP",  "BLTE",  "BLVU",  "BNST",  "BOBO",  "BOCH",  "BOGU",  
              "BOWA",  "BRAN",  "BRBL",  "BRBO",  "BRCR", "BRNO",  "BRPE",  "BRSP",  "BRTE",  "BRTH",  
              "BTBW",  "BTGR",  "BTGU",  "BTNW",  "BUFF",  "BUPE",  "BUTE",  "BVSH", "BWTE",  "BWWA",  
              "CAAU",  "CACH",  "CAEG",  "CAGU",  "CANG",  "CANV",  "CARW",  "CASW",  "CATE",  "CAWA",  
              "CEDW", "CHAR",  "CHIC",  "CHSP",  "CHSW",  "CLRA",  "CLSW",  "CMWA",  "COEI",  "COGA",  
              "COGO",  "COGR",  "COHA",  "COLO", "COME",  "COMO",  "COMU",  "CONI",  "COPE",  "CORA",  
              "CORE",  "COSH",  "COSN",  "COTE",  "COYE",  "CVSH",  "DASC", "DCCO",  "DEJU",  "DOVE",  
              "DOWI",  "DOWO",  "DUNL",  "EABL",  "EAKI",  "EAME",  "EAPH",  "EASO",  "EATO", "EISC", 
              "EUOY",  "EUSP",  "EUST",  "EUWI",  "EVGR",  "FALC",  "FEPE",  "FFSH",  "FICR",  "FISP",  
              "FOSP",  "FOTE",  "FRGU", "FTSP",  "GADW",  "GBBG",  "GBHE",  "GBHG",  "GBTE",  "GCKI",  
              "GHGH",  "GHOW",  "GLGU",  "GLIB",  "GOME",  "GRAJ", "GRAK",  "GRCA",  "GRCO",  "GREG",  
              "GRFR",  "GRHE",  "GRSC",  "GRSH",  "GRSK", "GRSP",  "GRYE", "GUTE",  "GWFG", "GWGU",  
              "GWTE", "HADU",  "HAPE",  "HAWK",  "HAWO",  "HEPE",  "HERG",  "HETH",  "HOFI",  "HOGR",  
              "HOLA",  "HOME", "HORE",  "HOSP",  "HOWA",  "HOWR",  "HUGO",  "ICGU",  "INBU",  "IVGU",  
              "JFPE",  "JUNC",  "KIEI",  "KILL",  "KIRA", "KUGU",  "LAGU",  "LALO",  "LBBG",  "LBDO",  
              "LBHE",  "LEAS",  "LENO",  "LEOW",  "LESA",  "LESC",  "LESP",  "LETE", "LEYE",  "LIGU",  
              "LISH",  "LISP",  "LITE",  "LONG",  "LOSH",  "LSGB",  "LSGW",  "LTDU",  "LTJA",  "MABO",  
              "MAFR", "MAGO",  "MALL",  "MASH",  "MAWA",  "MAWR",  "MEAD",  "MEGU",  "MERL",  "MODO",  
              "MOPL",  "MOWA",  "MUSW",  "MYWA", "NAWA",  "NHOW",  "NOBO",  "NOCA",  "NOFL",  "NOFU",  
              "NOGA",  "NOGO",  "NOHA",  "NOMO",  "NOPA",  "NOPI",  "NOTE", "NOWA",  "NRWS",  "NSHO",  
              "NSHR",  "NSTS",  "NSWO",  "OCWA",  "OROR",  "OSPR",  "OVEN",  "PAJA",  "PALO",  "PAWA", 
              "PBGR",  "PECO",  "PEEP",  "PEFA",  "PELI",  "PESA",  "PFSH",  "PHVI",  "PIGR",  "PIPL",  
              "PISI",  "PIWA",  "PIWO","POJA",  "POSP",  "PRAW",  "PROW",  "PUFI",  "PUMA",  "PUSA",  
              "RAZO",  "RBGR",  "RBGU",  "RBME",  "RBNU", "RBTR", "RBWO",  "RCKI",  "RECR",  "REDH",  
              "REDP",  "REEG",  "REKN",  "REPH",  "REVI",  "RFBO",  "RHAU",  "RHWO",  "RITD", "RLHA",  
              "RNDU",  "RNEP",  "RNGR",  "RNPH",  "ROPI",  "ROSP",  "ROST",  "ROSW",  "ROYT",  "RSHA",  
              "RTHA",  "RTHU", "RTLO",  "RTTR",  "RUBL",  "RUDU",  "RUGR",  "RUTU",  "RWBL",  "SACR",  
              "SAGU",  "SAND",  "SATE",  "SAVS",  "SBDO", "SBGU",  "SCAU",  "SCRE",  "SCTA",  "SEOW",  
              "SEPL",  "SESA",  "SEWR",  "SHAG",  "SHOR",  "SNBU",  "SNEG",  "SNGO", "SNOW",  "SOGU",  
              "SORA",  "SOSA",  "SOSH",  "SOSP",  "SOTE",  "SPAR",  "SPEI",  "SPGR",  "SPGU",  "SPPI",  
              "SPSA", "SPSK",  "SSHA",  "STEI",  "STSA",  "STSH",  "SUSC",  "SWAL",  "SWAN",  "SWIS",  
              "SWSP",  "TAPE",  "TBMU",  "TEWA", "THGU",  "TOSH",  "TRES",  "TRHE",  "TRSP",  "TUPU",  
              "TUSW",  "TUTI",  "TUVU",  "UAHA",  "UALB",  "UBBG",  "UBST", "UCAT",  "UCRT",  "UDAB",  
              "UDGS",  "UGOO",  "UGUI",  "UHGP",  "ULSB",  "UNAL",  "UNAM",  "UNBI",  "UNBL",  "UNBO", 
              "UNCA",  "UNCO",  "UNCR",  "UNDD",  "UNDU",  "UNEG",  "UNEI",  "UNFI",  "UNFL",  "UNFR",  
              "UNGB",  "UNGO",  "UNGR", "UNGU",  "UNHE",  "UNHU",  "UNJA",  "UNLA",  "UNLG",  "UNLO",  
              "UNLR",  "UNLS",  "UNLT",  "UNME",  "UNMT",  "UNMU", "UNNH",  "UNNI",  "UNOR",  "UNOW",  
              "UNPA",  "UNPE",  "UNPH",  "UNPR",  "UNPT",  "UNPU",  "UNRP",  "UNSA",  "UNSC","UNSG",  
              "UNSH",  "UNSK",  "UNSP",  "UNSS",  "UNST",  "UNSU",  "UNTA",  "UNTB",  "UNTE",  "UNTH",  
              "UNTL",  "UNVI", "UNWA",  "UNYE",  "USAC",  "USAN",  "USOW",  "USSB",  "VERM",  "VESP",  
              "VIRA",  "WAPI", "WBNU", "WBSP",  "WCSP", "WCTE",  "WEGU",  "WESA", "WEVI", "WFSP",  
              "WHIB",  "WHIM",  "WHTE",  "WILL",  "WIPH",  "WIPL",  "WISN",  "WISP", "WITU",  "WIWA",  
              "WIWR",  "WODU",  "WOTH",  "WRSA",  "WRSP",  "WTSH",  "WTSP",  "WTTR",  "WWBT",  "WWCR",  
              "WWDO", "WWGU",  "WWSC",  "XAMU",  "YBCH",  "YBCU",  "YBFL",  "YBSA",  "YCNH",  "YESH",  
              "YHBL",  "YLGU",  "YNAL",  "YRWA", "YWAR",  "ASDO",  "BBWH",  "BESE",  "BLWH",  "BODO",  
              "BRDO",  "CBWH",  "CLDO",  "CODO",  "DPSW",  "DSWH",  "FIWH","FKWH",  "FRDO",  "GBWH",  
              "GRSE",  "HAPO",  "HASE",  "HOSE",  "HRPS",  "HUWH",  "KIWH",  "LFPW",  "LSSD",  "MHDO", 
              "MIWH",  "NABW",  "PIWH",  "PKWH",  "PSDO",  "PSWH",  "RIDO",  "RISE",  "RIWH",  "RTDO",  
              "SBWH",  "SEWH",  "SFWH", "SPDO",  "SPWH",  "STDO",  "TBWH",  "UBKW",  "UNBW",  "UNCD",  
              "UNCE",  "UNDO",  "UNFS",  "UNGD",  "UNLD", "UNLW", "UNMM",  "UNPO",  "UNRO",  "UNSE",  
              "UNSW",  "UNTW",  "UNWH",  "UNZI",  "UTSE",  "WALR",  "WBDO",  "WIMA", "WSDO", "ALTU",  
              "BASH",  "BFTU",  "BIFI",  "BLAT",  "BLMA",  "BLSH",  "BLUE",  "BONI",  "CNRA",  "FAAL",  
              "FISH",  "GOMR", "GWSH", "HASH",  "KIMA",  "MAKO",  "MAMA",  "MARA",  "MOLA",  "OWTS",  
              "SAFI",  "SAIL",  "SCHA",  "SHAR",  "SKTU", "SPMA",  "SWFI",  "THHE",  "TUNA",  "UFFI",  
              "UNEL",  "UNLF",  "UNRA",  "UNSF",  "UNSR",  "UNTS",  "WAHO",  "WHMA", "YETU",  "ALGA",  
              "ANTE",  "BAIT",  "BALN",  "BDDR",  "BLST",  "BOAC",  "BOAT",  "BOBA",  "BOCA",  "BOCF",  
              "BOCG", "BOCR",  "BOCS",  "BOFE",  "BOFI",  "BOLO",  "BOME",  "BONA",  "BOPL",  "BOPS",  
              "BORF",  "BORV",  "BOSA",  "BOSU", "BOTA",  "BOTD",  "BOTU",  "BOWW",  "BOYA",  "BSTB",  
              "BUMB",  "BUOY",  "CAJE",  "CHAN",  "CLSU",  "DRAG",  "ERRO", "FGGI",  "FGLO",  "FGUN",  
              "FIGE",  "FLJE",  "FUEL",  "GISW",  "GRDA",  "HOCR",  "ICE",  "KRILL", "LABA", "LINE", 
              "MACR",  "MONA",  "MOON",  "MYBA",  "NONE",  "OCFR",  "ORSU",  "PLAS",  "PLBU",  "PMOW",  
              "POBE",  "PONY",  "RCKW", "REBA",  "SARG",  "SPEN",  "SUBU",  "SWDA",  "TOWR",  "TRAN",  
              "UBAT",  "UBUT",  "UFOB",  "UNCT",  "UNJE",  "UNKN", "UNMO",  "WAGL",  "ZOOP",  "GRTU",  
              "HATU",  "KRST",  "LETU",  "LOTU",  "SMTU",  "TURT",  "UNCH"),
            c("American Black Duck X Mallard Hybrid",     
              "American Black Duck",                                              
              "American Bittern",                                                 
              "American Coot", 
              "American Crow",  
              "American Goldfinch",  
              "American Golden Plover", 
              "American Kestrel",  
              "American Oystercatcher",   
              "American Pipit", 
              "American Redstart", 
              "American Robin",   
              "American Wigeon", 
              "American Woodcock", 
              "Anhinga anhinga",  
              "Arctic Loon/Pacific Loon", 
              "Arctic Loon",    
              "Arctic Tern",   
              "Atlantic Puffin",  
              "American Tree Sparrow", 
              "Audubon's Shearwater", 
              "American White Pelican",
              "Bald Eagle",     
              "Barrow's Goldeneye", 
              "Barn Owl",              
              "Bank Swallow", 
              "Baltimore Oriole", 
              "Barred Owl",  
              "Barn Swallow",
              "Baird's Sandpiper", 
              "Black-and-white Warbler",  
              "Black-billed Cuckoo",    
              "Black-bellied Plover",  
              "Black-bellied Storm-petrel",   
              "Black-backed Woodpecker",
              "Black-capped Chickadee", 
              "Black-crowned Night-Heron",
              "Black-capped Petrel", 
              "Belted Kingfisher",    
              "Bermuda Petrel",     
              "Black-footed Albatross", 
              "Blue-gray Gnatcatcher", 
              "Brown-headed Cowbird",
              "Common Black-headed Gull",
              "Blackburnian Warbler",
              "Black Guillemot", 
              "Blue Jay",       
              "Black-legged Kittiwake",
              "Black Noddy",   
              "Black Oystercatcher",
              "Blackpoll Warbler",
              "Black Scoter", 
              "Black Skimmer", 
              "Black Storm-petrel", 
              "Black Tern",  
              "Black Vulture",
              "Black-necked Stilt",
              "Bobolink",  
              "Boreal Chickadee",
              "Bonaparte's Gull",
              "Bohemian Waxwing",
              "Brant", 
              "Brewer's Blackbird",
              "Brown Booby",
              "Brown Creeper", 
              "Brown Noddy", 
              "Brown Pelican",
              "Band-rumped Storm-petrel",
              "Bridled Tern", 
              "Brown Thrasher",
              "Black-throated Blue Warbler",
              "Boat-tailed Grackle",
              "Black-tailed Gull",
              "Black-throated Green Warbler", 
              "Bufflehead", 
              "Bulwer's Petrel",
              "Unidentified Buteo", 
              "Black-vented Shearwater",
              "Blue-winged Teal", 
              "Blue-winged Warbler",
              "Cassin's Auklet", 
              "Carolina Chickadee",
              "Cattle Egret", 
              "California Gull",
              "Canada Goose",
              "Canvasback", 
              "Carolina Wren",
              "Cave Swallow",
              "Caspian Tern",
              "Canada Warbler",
              "Cedar Waxwing",
              "Unidentified Charadriiform",
              "Unidentified Chickadee", 
              "Chipping Sparrow",
              "Chimney Swift", 
              "Clapper Rail",
              "Cliff Swallow",
              "Cape May Warbler",
              "Common Eider",
              "Common Gallinule",
              "Common Goldeneye", 
              "Common Grackle", 
              "Cooper's Hawk",
              "Common Loon",
              "Common Merganser",  
              "Common Moorhen", 
              "Common Murre", 
              "Common Nighthawk",
              "Cook's Petrel",   
              "Common Raven",
              "Common Redpoll",
              "Cory's Shearwater",
              "Common Snipe", 
              "Common Tern", 
              "Common Yellowthroat",
              "Cape Verde Shearwater",
              "Unidentified Dark scoter - black or surf", 
              "Double-crested Cormorant",  
              "Dark-eyed Junco",  
              "Dovekie",  
              "Unidentified Dowitcher spp.",  
              "Downy Woodpecker",    
              "Dunlin",
              "Eastern Bluebird",  
              "Eastern Kingbird", 
              "Eastern Meadowlark", 
              "Eastern Phoebe",  
              "Eastern Screech-Owl",  
              "Eastern Towhee", 
              "Unidentified Eider/Scoter spp.", 
              "Eurasian Oystercatcher",   
              "European Storm-petrel",  
              "European Starling",  
              "Eurasian Wigeon", 
              "Evening Grosbeak", 
              "Unidentified falcon",  
              "Fea's Petrel",   
              "Flesh-footed Shearwater", 
              "Fish Crow",  
              "Field Sparrow", 
              "Fox Sparrow", 
              "Forster's Tern",
              "Franklin's Gull", 
              "Fork-tailed Storm-petrel", 
              "Gadwall",     
              "Great Black-backed Gull",
              "Great Blue Heron",  
              "Unidentified Great Black-backed/Herring Gull",  
              "Gull-billed Tern", 
              "Golden-crowned Kinglet", 
              "Glaucous Gull X Herring Gull (hybrid)",
              "Great Horned Owl",  
              "Glaucous Gull",
              "Glossy Ibis", 
              "Unidentified Goldeneye or Merganser",
              "Gray Jay", 
              "Gray Kingbird",
              "Gray Catbird",  
              "Great Cormorant", 
              "Great Egret", 
              "Great Frigatebird", 
              "Green Heron", 
              "Greater Scaup",
              "Greater Shearwater", 
              "Great Skua",  
              "Grasshopper Sparrow", 
              "Greater Yellowlegs",
              "Unidentified Small Gull/Tern",
              "Greater White-fronted Goose", 
              "Glaucous-winged Gull", 
              "Green-winged Teal", 
              "Harlequin Duck",
              "Hawaiian Petrel",  
              "Unidentified hawk", 
              "Hairy Woodpecker",   
              "Herald Petrel", 
              "Herring Gull", 
              "Hermit Thrush", 
              "House Finch",  
              "Horned Grebe", 
              "Horned Lark",  
              "Hooded Merganser", 
              "Hoary Redpoll", 
              "House Sparrow",
              "Hooded Warbler", 
              "House Wren",   
              "Hudsonian Godwit",
              "Iceland Gull",
              "Indigo Bunting",
              "Ivory Gull",
              "Juan Fernandez Petrel ssp.", 
              "Unidentified junco", 
              "King Eider", 
              "Killdeer",
              "King Rail", 
              "Kumlien's Gull", 
              "Laughing Gull",
              "Lapland Longspur",
              "Lesser Black-backed Gull",  
              "Long-billed Dowitcher",
              "Little Blue Heron",  
              "Least Storm-petrel", 
              "Lesser Noddy",      
              "Long-eared Owl",
              "Least Sandpiper",
              "Lesser Scaup", 
              "Leach's Storm-petrel", 
              "Least Tern",
              "Lesser Yellowlegs",
              "Little Gull", 
              "Little Shearwater", 
              "Lincoln's Sparrow",
              "Little Tern",
              "Unidentified Longspur",
              "Loggerhead Shrike", 
              "Lesser Snow Goose, Blue Phase",
              "Lesser Snow Goose, White phase",
              "Long-tailed Duck", 
              "Long-tailed Jaeger",
              "Masked Booby", 
              "Magnificent Frigatebird",
              "Marbled Godwit",
              "Mallard",
              "Manx Shearwater",
              "Magnolia Warbler",
              "Marsh Wren", 
              "Unidentified Meadowlark",
              "Mew Gull", 
              "Merlin", 
              "Mourning Dove",
              "Mountain Plover", 
              "Mourning Warbler",
              "Mute Swan", 
              "Myrtle Warbler",
              "Nashville Warbler",
              "Northern Hawk Owl",
              "Northern Bobwhite",
              "Northern Cardinal",
              "Northern Flicker",
              "Northern Fulmar", 
              "Northern Gannet", 
              "Northern Goshawk",
              "Northern Harrier",
              "Northern Mockingbird",
              "Northern Parula",
              "Northern Pintail",
              "Unidentified Noddy Tern",  
              "Northern Waterthrush",  
              "Northern Rough-winged Swallow", 
              "Northern Shoveler",  
              "Northern Shrike", 
              "Nelson's Sharp-tailed Sparrow", 
              "Northern Saw-whet Owl",
              "Orange-crowned Warbler", 
              "Orchard Oriole", 
              "Osprey",
              "Ovenbird",
              "Parasitic Jaeger",
              "Pacific Loon", 
              "Palm Warbler", 
              "Pied-billed Grebe",
              "Pelagic Cormorant",
              "Unidentified peep", 
              "Peregrine Falcon",
              "Unidentified Pelican",
              "Pectoral Sandpiper",
              "Pink-footed Shearwater", 
              "Philadelphia Vireo", 
              "Pine Grosbeak",
              "Piping Plover",
              "Pine Siskin",
              "Pine Warbler",
              "Pileated Woodpecker",
              "Pomarine Jaeger",
              "Polynesian Storm-petrel",
              "Prairie Warbler",
              "Prothonotary Warbler",
              "Purple Finch",
              "Purple Martin",
              "Purple Sandpiper",
              "Razorbill",
              "Rose-breasted Grosbeak",
              "Ring-billed Gull", 
              "Red-breasted Merganser",
              "Red-breasted Nuthatch",
              "Red-billed Tropicbird",
              "Red-bellied Woodpecker",
              "Ruby-crowned Kinglet",
              "Red Crossbill",  
              "Redhead", 
              "Common or Hoary Redpoll",
              "Reddish Egret",
              "Red Knot", 
              "Red Phalarope",
              "Red-eyed Vireo", 
              "Red-footed Booby", 
              "Rhinoceros Auklet", 
              "Red-headed Woodpecker",
              "Ringed Turtle-Dove", 
              "Rough-legged Hawk",
              "Ring-necked Duck",
              "Ring-necked Pheasant",
              "Red-necked Grebe", 
              "Red-necked Phalarope",
              "Rock Pigeon",
              "Roseate Spoonbill",
              "Roseate Tern",  
              "Rough-Winged Swallow",
              "Royal Tern",
              "Red-shouldered Hawk",
              "Red-tailed Hawk", 
              "Ruby-throated Hummingbird",
              "Red-throated Loon",
              "Red-tailed Tropicbird",
              "Rusty Blackbird",
              "Ruddy Duck", 
              "Ruffed Grouse",
              "Ruddy Turnstone" , 
              "Red-winged Blackbird", 
              "Sandhill Crane", 
              "Sabine's Gull",
              "Sanderling", 
              "Sandwich Tern",
              "Savannah Sparrow", 
              "Short-billed Dowitcher",
              "Slaty-backed Gull",  
              "Unidentified Scaup",  
              "Unidentified screech-owl", 
              "Scarlet Tanager", 
              "Short-eared Owl", 
              "Semipalmated Plover", 
              "Semipalmated Sandpiper",
              "Sedge Wren",      
              "Shag",       
              "Unidentified shorebird",
              "Snow Bunting",
              "Snowy Egret", 
              "Snow Goose",
              "Snowy Owl", 
              "Sooty Gull", 
              "Sora",    
              "Solitary Sandpiper", 
              "Sooty Shearwater",
              "Song Sparrow", 
              "Sooty Tern",  
              "Unidentified sparrow",
              "Spectacled Eider", 
              "Spruce Grouse",  
              "Spectacled Guillemot",
              "Sprague's Pipit",
              "Spotted Sandpiper", 
              "South Polar Skua",  
              "Sharp-shinned Hawk",
              "Steller's Eider",
              "Stilt Sandpiper",
              "Short-tailed Shearwater",
              "Surf Scoter",   
              "Unidentified Swallow", 
              "Unidentified Swan", 
              "Swinhoe's Storm-petrel",
              "Swamp Sparrow",
              "Tahiti Petrel",
              "Thick-billed Murre",
              "Tennessee Warbler",
              "Thayer's Gull",
              "Townsend's Shearwater",
              "Tree Swallow", 
              "Tricolored (Louisiana) Heron",
              "Tristram's Storm-Petrel",
              "Tufted Puffin", 
              "Tundra Swan",
              "Tufted Titmouse",
              "Turkey Vulture", 
              "Unidentified Accipiter Hawk",
              "Unidentified Albatross",
              "Unidentified Great or Lesser Black-backed Gull",
              "Bridled or Sooty Tern",
              "Common or Arctic Tern", 
              "Unidentified Common or Roseate Tern", 
              "Unidentified dabbling duck", 
              "Unidentified Duck, Goose, or Swan",
              "Unidentified Goose",
              "Unidentified Guillemot", 
              "Unidentified Hawaiian Petrel or Galapagos Petrel",
              "Unidentified large shorebird", 
              "Unidentified Alcid",  
              "Unidentified Seaside or Sharptailed Sparrow",
              "Unidentified Bird", 
              "Unidentified Blackbird", 
              "Unidentified Booby", 
              "Unidentified Calidris (Sandpiper, Sanderling, Dunlin, Red Knot)",  
              "Unidentified Cormorant", 
              "Unidentified Crow",  
              "Unidentified Diving/Sea Duck", 
              "Unidentified Duck",
              "Unidentified Egret",   
              "Unidentified Eider",
              "Unidentified Finch", 
              "Unidentified Flycatcher", 
              "Unidentified Frigatebird",
              "Unidentified Goldeneye/Bufflehead", 
              "Unidentified Goldeneye",  
              "Unidentified Grebe", 
              "Unidentified Gull", 
              "Unidentified Heron", 
              "Unidentified Hummingbird", 
              "Unidentified Jaeger", 
              "Unidentified large alcid (Razorbill or Murre)",
              "Unidentified Large Gull",
              "Unidentified Loon",
              "Unidentified large rail", 
              "Unidentified Large Shearwater",
              "Unidentified large Tern", 
              "Unidentified Merganser", 
              "Unidentified medium tern",
              "Unidentified Murre", 
              "Unidentified Night Heron",
              "Unidentified Nighthawk",
              "Unidentified Oriole",
              "Unidentified Owl",
              "Unidentified Passerine (perching birds, songbirds)", 
              "Unidentified Petrel",
              "Unidentified Phalarope",
              "Unidentified tubenose", 
              "Unidentified Pterodroma (petrels)",
              "Unidentified Puffin",    
              "Unidentified Raptor/ bird of prey", 
              "Unidentified small alcid (Puffin/Dovekie)",  
              "Unidentified Scoter", 
              "Unidentified small gull", 
              "Unidentified Shearwater", 
              "Unidentified Skua", 
              "Unidentified Storm-petrel", 
              "Unidentified Small Shearwater (Audubon's, Manx, or Little)", 
              "Unidentified small Tern", 
              "Unidentified Sulid",
              "Unidentified Tanager", 
              "Unidentified Tropicbird", 
              "Unidentified Tern", 
              "Unidentified Thrush",
              "Unidentified Teal",  
              "Unidentified Vireo", 
              "Unidentified Warbler", 
              "Unidentified Yellowlegs", 
              "Unidentified small Accipiter",
              "Unidentified Sandpiper",
              "Unidentified small owl", 
              "Unidentified small shorebird", 
              "Unidentified Vermivora", 
              "Vesper Sparrow",
              "Virginia Rail", 
              "Water Pipit", 
              "White-breasted Nuthatch", 
              "White-bellied Storm-petrel",
              "White-crowned Sparrow", 
              "White-cheeked Tern", 
              "Western Gull",  
              "Western Sandpiper", 
              "White-eyed Vireo", 
              "White-faced Storm-petrel", 
              "White Ibis", 
              "Whimbrel", 
              "White Tern", 
              "Willet", 
              "Wilson's phalarope",
              "Wilson's Plover",  
              "Wilson's Snipe", 
              "Wilson's Storm-petrel",
              "Wild Turkey",
              "Wilson's Warbler", 
              "Winter Wren", 
              "Wood Duck", 
              "Wood Thrush",
              "White-rumped Sandpiper",
              "Wedge-rumped Storm-petrel", 
              "Wedge-tailed Shearwater", 
              "White-throated Sparrow", 
              "White-tailed Tropicbird",
              "White-winged Black Tern", 
              "White-winged Crossbill", 
              "White-winged Dove",    
              "Unidentified white winged gull (Ross's Gull, Ivory Gull, Iceland Gull, Glaucous-winged Gull and Glaucous Gull)",
              "White-winged Scoter", 
              "Xantus' Murrelet",   
              "Yellow-breasted Chat", 
              "Yellow-billed Cuckoo",
              "Yellow-bellied Flycatcher", 
              "Yellow-bellied Sapsucker", 
              "Yellow-crowned Night Heron", 
              "Yelkouan Shearwater",
              "Yellow-headed Blackbird", 
              "Yellow-legged Gull",    
              "Yellow-nosed Albatross",   
              "Yellow-rumped Warbler", 
              "Yellow Warbler",        
              "Atlantic Spotted Dolphin", 
              "Blainville's Beaked Whale",  
              "Bearded Seal",     
              "Blue Whale",   
              "Bottlenose Dolphin", 
              "Bridled Dolphin", 
              "Cuvier's Beaked Whale",
              "Clymene Dolphin", 
              "Common Dolphin",  
              "Unidentified Dwarf/Pygmy Sperm Whale",  
              "Dwarf Sperm Whale", 
              "Fin Whale",
              "False Killer Whale",
              "Fraser's Dolphin",
              "Gervais' Beaked Whale",
              "Gray Seal",
              "Harbor Porpoise", 
              "Harbor Seal", 
              "Hooded Seal",
              "Harp Seal", 
              "Humpback Whale",
              "Killer Whale",
              "Long-finned Pilot Whale", 
              "Long-snouted Spinner Dolphin",
              "Melon-headed Whale",  
              "Minke Whale",  
              "North Atlantic Bottle-nosed whale", 
              "Pilot Whale",  
              "Pygmy Killer Whale",
              "Pantropical Spotted Dolphin", 
              "Pygmy Sperm Whale",  
              "Risso's dolphin", 
              "Ringed Seal",
              "Right Whale", 
              "Rough-toothed Dolphin",
              "Sowerby's Beaked Whale", 
              "Sei Whale",  
              "Short-finned Pilot Whale",  
              "Unidentified Spotted Dolphins (Atlantic or Pantropical)", 
              "Sperm Whale",   
              "Striped Dolphin", 
              "True's Beaked Whale", 
              "Unidentified Beaked Whale", 
              "Unidentified Baleen Whale",  
              "Unidentified Common Dolphins", 
              "Unidentified Cetacean",
              "Unidentified Dolphin", 
              "Unidentified Fin/Sei whale",
              "Unidentified Spotted or Bottlenose Dolphin", 
              "Unidentified Lagenorhynchus dolphin", 
              "Unidentified large whale",
              "Unidentified Marine Mammal",
              "Unidentified porpoise", 
              "Unidentified Rorqual",
              "Unidentified Seal", 
              "Unidentified small whale", 
              "Unidentified Toothed Whales", 
              "Unidentified Whale",
              "Unidentified Ziphiid (beaked whale)",
              "Unidentified True Seal",
              "Walrus",         
              "White-beaked Dolphin",
              "West Indian Manatee",  
              "Atlantic White-sided Dolphin", 
              "Albacore Tuna",  
              "Basking Shark", 
              "Atlantic Bluefin Tuna",
              "Billfishes", 
              "Blackfin Tuna", 
              "Blue Marlin", 
              "Blue Shark", 
              "Bluefish", 
              "Bonito", 
              "Cownose Ray", 
              "False Albacore",
              "Unidentified fish", 
              "Giant Oceanic Manta Ray",
              "Great White Shark", 
              "Hammerhead shark", 
              "King Mackerel", 
              "Unidentified Long-finned/Short-finned Mako Shark",
              "Dolphin fish (Mahi-Mahi)", 
              "Unidentified Manta Ray",
              "Ocean Sunfish (Mola)",
              "Oceanic Whitetip Shark (aka. Brown shark, brown Milbert's sand bar shark, nigano shark, silvertip shark)",
              "Sargassumfish", 
              "Sailfish",   
              "Scalloped Hammerhead Shark", 
              "Unidentified shark", 
              "Skipjack Tuna", 
              "Spanish mackerels", 
              "Unidentified Swordfish spp.",
              "Thread Herrings", 
              "Unidentified tuna",
              "Unidentified flying fish",
              "Unidentified elasmobranch (Shark, Ray, Skate)",
              "Unidentified large fish",  
              "Unidentified ray", 
              "Unidentified small fish", 
              "Unidentified stringray", 
              "Unidentified thresher shark", 
              "Wahoo",    
              "White Marlin", 
              "Yellowfin Tuna", 
              "Algal bloom", 
              "Antennae", 
              "bait ball", 
              "balloon", 
              "Blue Dasher Dragonfly",  
              "Black Swallowtail",
              "Boat--aircraft carrier",
              "Boat--unidentified",  
              "Boat--barge/barge and tug",
              "Boat--cargo", 
              "Boat--commercial fishing",  
              "Boat--Coast Guard", 
              "Boat--cruise", 
              "Boat--container ship",
              "Boat--Ferry", 
              "Boat--Fishing", 
              "boat--lobster", 
              "Boat--merchant",
              "Boat--navy", 
              "Boat--pleasure",
              "Boat--purseiner", 
              "Boat--recreational fishing",
              "Boat--research vessel", 
              "Boat--sail", 
              "Boat--submarine", 
              "Boat--tanker",   
              "Boat--trawler/dragger",   
              "Boat--tug", 
              "Boat--whale watch", 
              "Boat--yacht", 
              "Black Swallowtail Butterfly",   
              "Unidentified Bee",   
              "buoy", 
              "Cannonball Jelly", 
              "Change in personnel, station, transect, etc.", 
              "Cloudless Sulphur", 
              "dragonfly spp.", 
              "error",  
              "fixed gear--gill net",
              "fixed gear--lobster",  
              "fixed gear--unidentified",
              "fishing gear",
              "flotsam and jetsam", 
              "oil/fuel",
              "Giant Swallowtail Butterfly", 
              "Green Darner",
              "Atlantic Horseshoe Crab",
              "ice",
              "Unidentified krill", 
              "Latex balloon",
              "rope/line", 
              "macroalgae", 
              "Monarch Butterfly",
              "Moon Jellyfish",  
              "Mylar balloon",
              "none",  
              "ocean front", 
              "Orange Sulphur", 
              "plastic",  
              "Painted Lady Butterfly",
              "Portuguese Man o' War",
              "Polar Bear", 
              "Pony", 
              "rockweed", 
              "Red Bat",
              "Sargassum", 
              "Salmon Pens", 
              "Sulfur Butterfly spp.",
              "Swamp Darner", 
              "Tower", 
              "transect point",
              "Unidentified Bat", 
              "Unidentified butterfly",
              "Unidentified flying object (animal-origin)",  
              "??",  
              "Unidentified jellyfish",
              "unknown", 
              "Unidentified Moth", 
              "Wandering Glider",
              "zooplankton", 
              "Green Turtle",
              "Hawksbill Turtle", 
              "Kemp's Ridley Sea Turtle",
              "Leatherback Turtle", 
              "Loggerhead Turtle", 
              "Unidentified Small turtle - Loggerhead, Green, Hawksbill, or Kemp's Ridley",
              "Unidentified Sea Turtle",  
              "Unidentified Cheloniidae species (Green Sea Turtle, Hawksbill Sea Turtle, and Flatback Sea Turtle)"),
            c("Anas rubripes x platy.",
              "Anas rubripes",
              "Botaurus lentiginosus",
              "Fulica americana",
              "Corvus brachyrhynchos",
              "Carduelis tristis",
              "Pluvialis dominica",
              "Falco sparverius",
              "Haematopus palliatus",
              "Anthus rubescens",
              "Setophaga ruticilla",
              "Turdus migratorius",
              "Anas americana",
              "Scolopax minor",
              "Anhinga anhinga",
              "Gavia arctica/pacifica",
              "Gavia arctica",
              "Sterna paradisaea",
              "Fratercula arctica",
              "Spizella arborea",
              "Puffinus iherminieri",
              "Pelecanus erythrorhynchos",
              "Haliaeetus leucocephalus",
              "Bucephala islandica",
              "Tyto alba",
              "Riparia riparia",
              "Icterus galbula",
              "Strix varia",
              "Hirundo rustica",
              "Calidris bairdii",
              "Mniotilta varia",
              "Coccyzus erythropthalmus",
              "Pluvialis squatarola",
              "Fregetta tropica",
              "Picoides arcticus",
              "Poecile atricapillus",
              "Nycticorax nycticorax",
              "Pterodroma hasitata",
              "Megaceryle alcyon",
              "Pterodroma cahow",
              "Diomedea nigripes",
              "Polioptila caerulea",
              "Molothrus ater",
              "Larus ridibundus",
              "Dendroica fusca",
              "Cepphus grylle",
              "Cyanocitta cristata",
              "Rissa tridactyla",
              "Anous minutus",
              "Haematopus bachmani",
              "Dendroica striata",
              "Melanitta nigra",
              "Rynchops niger",
              "Oceanodroma melania",
              "Chlidonias niger",
              "Coragyps atratus",
              "Himantopus mexicanus",
              "Dolichonyx oryzivorus",
              "Poecile hudsonica",
              "Larus philadelphia",
              "Bombycilla garrulus",
              "Branta bernicla",
              "Euphagus cyanocephalus",
              "Sula leucogaster",
              "Certhia americana",
              "Anous stolidus",
              "Pelecanus occidentalis",
              "Oceanodroma castro",
              "Sterna anaethetus",
              "Toxostoma rufum",
              "Dendroica caerulescens",
              "Quiscalus major",
              "Larus crassirostris",
              "Dendroica virens",
              "Bucephala albeola",
              "Bulweria  Bulweria",
              "Buteo spp.",
              "Puffinus opisthomelas",
              "Anas discors",
              "Vermivora pinus",
              "Ptychoramphus aleuticus",
              "Poecile carolinensis",
              "Bubulcus ibis",
              "Larus californicus",
              "Branta canadensis",
              "Aythya valisineria",
              "Thryothorus ludovicianus",
              "Petrochelidon fulva",
              "Sterna caspia",
              "Cardellina canadensis",
              "Bombycilla cedrorum",
              "Charadriiformes spp.",
              "--",
              "Spizella passerina",
              "Chaetura pelagica",
              "Rallus longirostris",
              "Petrochelidon pyrrhonota",
              "Dendroica tigrina", 
              "Somateria mollissima",
              "Gallinula galeata",
              "Bucephala clangula",
              "Quiscalus quiscula",
              "Accipiter cooperii",
              "Gavia immer",
              "Mergus merganser",
              "Gallinula chloropus",
              "Uria aalge",
              "Chordeiles minor",
              "Pterodroma cookii",
              "Corvus corax",
              "Carduelis flammea",
              "Calonectris diomedea",
              "Gallinago gallinago",
              "Sterna hirundo",
              "Geothlypis trichas",
              "Calonectris edwardsii",
              "--", 
              "Phalacrocorax auritus",
              "Junco hyemalis",
              "Alle alle",
              "Limnodromus griseus or L. scolopaceus",
              "Picoides pubescens",
              "Calidris alpina",
              "Sialia sialis", 
              "Tyrannus tyrannus",
              "Sturnella magna",
              "Sayornis phoebe",
              "Megascops asio",
              "Pipilo erythrophthalmus",
              "Melanitta/Somateria spp.",
              "Haematopus ostralegus",
              "Hydrobates pelagicus",
              "Sturnus vulgaris",
              "Anas penelope",
              "Coccothraustes vespertinus",
              "Falco spp.",
              "Pterodroma feae",
              "Puffinus carneipes",
              "Corvus ossifragus",
              "Spizella pusilla",
              "Passerella iliaca",
              "Sterna forsteri",
              "Larus pipixcan",
              "Oceanodroma furcata",
              "Anas strepera",
              "Larus marinus", 
              "Ardea herodias",
              "Larus marinus/argentatus",
              "Sterna nilotica",
              "Regulus satrapa",
              "Larus hyperboreus X argentatus",
              "Bubo virginianus",
              "Larus hyperboreus",
              "Plegadis falcinellus",
              "--",
              "Perisoreus canadensis",
              "Tyrannus dominicensis",
              "Dumetella carolinensis",
              "Phalacrocorax carbo",
              "Ardea alba",
              "Fregata minor",
              "Butorides Virescens",
              "Aythya marila",
              "Puffinus gravis",
              "Stercorarius skua",
              "Ammodramus savannarum",
              "Tringa melanoleuca",
              "--",
              "Anser albifrons",
              "Larus glaucescens",
              "Anas crecca",
              "Histrionicus histrionicus",
              "Pterodroma sandwichensis",
              "--",
              "Picoides villosus",
              "Pterodroma arminjoniana",
              "Larus argentatus",
              "Catharus guttatus",
              "Carpodacus mexicanus",
              "Podiceps auritus", 
              "Eremophila alpestris",
              "Lophodytes cucullatus",
              "Carduelis hornemanni",
              "Passer domesticus",
              "Wilsonia citrinis",
              "Troglodytes aedon",
              "Limosa haemastica",
              "Larus glaucoides",
              "Passerina cyanea",
              "Pagophila eburnea",
              "Pterodroma externa externa",
              "--",
              "Somateria spectabilis",
              "Charadrius vociferus",
              "Rallus elegans",
              "Larus glaucoides kumlieni",
              "Larus atricilla",
              "Calcarius lapponicus" ,
              "Larus fuscus",
              "Limnodromus scolopaceus",
              "Egretta caerulea",
              "Oceanodroma microsoma",
              "Anous tenuirostris",
              "Asio otus",
              "Calidris minutilla",
              "Aythya affinis",
              "Oceanodroma leucorhoa",
              "Sterna antillarum",
              "Tringa flavipes",
              "Larus minutus",
              "Puffinus assimilis",
              "Melospiza lincolnii",
              "Sternula albifrons",
              "Calcarius spp.",
              "Lanius ludovicianus",
              "Chen caerulescens",
              "Chen caerulescens",
              "Clangula hyemalis", 
              "Stercorarius longicaudus",
              "Sula dactylatra",
              "Fregata magnificens",
              "Limosa fedoa",
              "Anas platyrhynchos",
              "Puffinus puffinus",
              "Dendroica magnolia",
              "Cistothorus palustris",
              "Sturnella  spp.",
              "Larus canus",
              "Falco columbarius",
              "Zenaida macroura",
              "Charadrius montanus",
              "Oporornis philadelphia",
              "Cygnus Olor",
              "Dendroica c. coronata",
              "Vermivora ruficapilla",
              "Surnia ulula",
              "Colinus virginianus",
              "Cardinalis cardinalis",
              "Colaptes auratus",
              "Fulmarus glacialis",
              "Morus bassanus",
              "Accipiter gentilis",
              "Circus cyaneus", 
              "Mimus polyglottos",
              "Parula americana",
              "Anas acuta",
              "--",
              "Seiurus noveboracensis",
              "Stelgidopteryx serripennis",
              "Anas clypeata",
              "Lanius excubitor",
              "Ammodramus nelsoni",
              "Aegolius acadicus",
              "Vermivora celata",
              "Icterus spurius",
              "Pandion haliaetus",
              "Seiurus aurocapillus",
              "Stercorarius parasiticus",
              "Gavia pacifica",
              "Dendroica palmarum", 
              "Podilymbus podiceps",
              "Phalacrocorax pelagicus",
              "--",
              "Falco peregrinus",
              "Pelecanus spp.",
              "Calidris melanotos",
              "Puffinus creatopus",
              "Vireo philadelphicus",
              "Pinicola enucleator",
              "Charadrius melodus",
              "Carduelis pinus",
              "Dendroica pinus",
              "Dryocopus pileatus",
              "Stercorarius pomarinus",
              "Nesofregetta fuliginosa",
              "Dendroica discolor",
              "Protonotaria citrea",
              "Carpodacus purpureus",
              "Progne subis",
              "Calidris maritima",
              "Alca torda",
              "Pheucticus ludovicianus",
              "Larus delawarensis",
              "Mergus serrator",
              "Sitta canadensis",
              "Phaethon aethereus",
              "Melanerpes carolinus",
              "Regulus calendula",
              "Loxia curvirostra",
              "Aythya americana",
              "Carduelis flammea/hornemanni",
              "Egretta rufescens",
              "Calidris canutus",
              "Phalaropus fulicaria",
              "Vireo olivaceous",
              "Sula sula",
              "Cerorhinca monocerata",
              "Melanerpes erythrocephalus",
              "Streptopelia risoria",
              "Buteo lagopus",
              "Aythya collaris",
              "Phasianus colchicus",
              "Podiceps grisegena",
              "Phalaropus lobatus",
              "Columba livia",
              "Platalea ajaja",
              "Sterna dougallii",
              "Stelgidopteryx sp.",
              "Sterna maxima",
              "Buteo lineatus",
              "Buteo jamaicensis",
              "Archilochus colubris",
              "Gavia stellata",
              "Phaethon rubricauda",
              "Euphagus carolinus",
              "Oxyura jamaicensis",
              "Bonasa umbellus",
              "Arenaria interpres",
              "Agelaius phoeniceus",
              "Grus canadensis",
              "Xema sabini",
              "Calidris alba",
              "Sterna sandvicensis",
              "Passerculus sandwichensis",
              "Limnodromus griseus",
              "Larus schistisagus",
              "Aythya marila or A. affinis"
              ,"--",
              "Piranga olivacea",
              "Asio flammeus",
              "Charadrius semipalmatus",
              "Calidris pusilla",
              "Cistothorus platensis",
              "Phalacrocorax aristotelis",
              "--",
              "Plectrophenax nivalis",
              "Egretta thula",
              "Chen caerulescens",
              "Bubo scandiacus",
              "Larus hemprichii",
              "Porzana carolina",
              "Tringa solitaria",
              "Puffinus griseus",
              "Melospiza melodia",
              "Sterna fuscata",
              "Emberizidae",
              "Somateria fischeri",
              "Falcipennis canadensis",
              "Cepphus carbo",
              "Anthus spragueii",
              "Actitis macularia",
              "Stercorarius maccormicki",
              "Accipiter striatus",
              "Polysticta stelleri",
              "Calidris himantopus",
              "Puffinus tenuirostris",
              "Melanitta perspicillata",
              "Hirundinidae",
              "Olor spp.",
              "Oceanodroma monorhis",
              "Melospiza georgiana",
              "Pseudobulweria rostrata",
              "Uria lomvia",
              "Vermivora peregrina",
              "Larus thayeri",
              "Puffinus auricularis",
              "Tachycineta bicolor",
              "Egretta tricolor",
              "Oceanodroma tristrami",
              "Fratercula cirrhata",
              "Cygnus columbianus",
              "Baeolophus bicolor",
              "Cathartes aura",
              "Accipiter spp.",
              "Diomedeidae spp.",
              "Larus marinus/fuscus",
              "Sterna anaethetus/fuscata",
              "Sterna hirundo/paradisaea",
              "Sterna hirundo/dougallii", 
              "--",
              "Anseriformes spp.",
              "--",
              "Cepphus spp.",
              "Pterodroma sandwichensis/phaeopygia",
              "--",
              "Alcidae spp.",
              "Ammodramus spp.",
              "Aves",
              "Icteridae spp.",
              "Sula spp.",
              "Calidris spp.",
              "Phalacrocorax spp",
              "Corvus spp.",
              "Aythya spp.",
              "--",
              "--",
              "Somateria spp.",
              "Carduelis spp.",
              "Empidonax spp.",
              "Fregata spp.",
              "Bucephala spp.",
              "Bucephala spp.",
              "Podiceps spp.",
              "--",
              "--",
              "Trochilidae",
              "Stercorarius spp.",
              "--",
              "--",
              "Gavia spp.",
              "Rallidae", 
              "--",
              "--",
              "--",
              "Sterna spp.",
              "Uria spp.",
              "--",
              "--",
              "Icterus spp.",
              "Strigidae",
              "--",
              "Procellariidae",
              "Phalaropus spp.",
              "Procellariidae",
              "Pterodroma spp.",
              "Fratercula spp.",
              "--", 
              "Alle alle/Fratercula arctica",
              "Melanitta spp.", 
              "--",
              "Procellariidae",
              "Stercorarius spp.",
              "--", 
              "Puffinus lherminieri , P. puffinus, or P. assimilis",
              "Sterna spp.",
              "Sulidae spp.",
              "--",
              "Phaethon spp.",
              "Sterna spp.", 
              "Turdidae spp.",
              "--", 
              "--",
              "--", 
              "Tringa melanoleuca or T. flavipes",
              "--", 
              "Scolopacidae spp.",
              "--",
              "--",
              "Vermivora", 
              "Pooecetes gramineus",
              "Rallus limicola",
              "Anthus spinoletta",
              "Sitta carolinensis",
              "Fregetta grallaria",
              "Zonotrichia leucophrys", 
              "Sterna repressa",
              "Larus occidentalis",  
              "Calidris mauri",
              "Vireo griseus",
              "Pelagodroma marina",
              "Eudocimus albus", 
              "Numenius phaeopus",
              "Gygis alba",
              "Catoptrophorus semipalmatus",
              "Phalaropus tricolor",
              "Charadrius wilsonia",
              "Gallinago delicata",
              "Oceanites oceanicus",
              "Meleagris gallopavo",
              "Wilsonia pusilla",
              "Troglodytes troglodytes",
              "Aix sponsa",
              "Hylocichla mustelina",
              "Calidris fuscicollis",
              "Oceanodroma tethys",
              "Puffinus pacificus",
              "Zonotrichia albicollis",
              "Phaethon lepturus",
              "Chlidonias leucopterus",
              "Loxia leucoptera",
              "Zenaida asiatica",
              "genus Larus",
              "Melanitta fusca",
              "Synthliboramphus hypoleucus",
              "Icteria virens",
              "Coccyzus americanus",
              "Empidonax flaviventris",
              "Sphyrapicus varius",
              "Nyctanassa violacea",
              "Puffinus yelkouan",
              "Xanthocephalus xanthocephalus",
              "Larus cachinnans",
              "Thalassarche chlororhynchos",
              "Dendroica coronata",
              "Dendroica petechia",
              "Stenella frontalis",
              "Mesoplodon densirstris",
              "Erignathus barbatus", 
              "Balaenoptera musculus",
              "Tursiops truncatus",
              "Stenella attenuata/ frontalis",
              "Ziphius cavirostris",
              "Stenella clymene",
              "Delphinus delphis",
              "Kogia simus or K. breviceps",
              "Kogia sima",
              "Balaenoptera physalus",
              "Pseudorca crassidens",
              "Lagenodelphis hosei",
              "Mesoplodon europaeus",
              "Halichoerus grypus", 
              "Phocoena phocoena",
              "Phoca vitulina",
              "Cystophora cristata",
              "Pagophilus groenlandicus",
              "Megaptera novaeangliae",
              "Orcinus orca",
              "Globicephala melas",
              "Stenella longirostris", 
              "Peponocephala electra",
              "Balaenoptera acutorostrata",
              "Hyperoodon ampullatus",
              "Globicephala",
              "Feresa attenuata",
              "Stenella attenuata",
              "Kogia breviceps",
              "Grampus griseus",
              "Pusa hispida",
              "Eubalaena glacialis",
              "Steno bredanensis",
              "Mesoplodon bidens",
              "Balaenoptera borealis",
              "Globicephala macrorhynchus",
              "Stenella spp.",
              "Physeter macrocephalus",
              "Stenella coeruleoalba",
              "Mesoplodon mirus", 
              "Mesoplodon spp.",
              "Mysticeti spp.",
              "Delphinus spp.",
              "Cetacea spp.",
              "Delphinidae",
              "Balaenoptera physalus/Balaenoptera borealis",
              "Stenella or Tursiops",
              "Lagenorhynchus sp.", 
              "Cetacea spp.",
              "Mammalia",
              "--",
              "Balaenopteridae spp.", 
              "Phocidae",
              "Cetacea spp.", 
              "Odontoceti spp.",
              "Cetacea spp.",
              "Ziphiidae",
              "Phocidae spp.",
              "Odobenus rosmarus",
              "Lagenorhynchus albirostris", 
              "Trichechus manatus",
              "Lagenorhynchus acutus",
              "Thunnus alalunga",
              "Cetorhinus maximus",
              "Thunnus thynnus",
              "Istiophoridae spp.",
              "Thunnus atlanticus",
              "Makaira nigricans",
              "Prionace glauca",
              "Pomatomus saltatrix",
              "Scombridae spp.",
              "Rhinoptera bonasus",
              "Euthynnus alletteratus",
              "Osteichthyes",
              "Manta birostris",
              "Carcharodon carcharias",
              "Sphyrnidae spp.",
              "Scomberomorus cavalla",
              "Isurus spp.",
              "Coryphaena hippurus",
              "Mobulidae",
              "Mola mola",
              "Carcharhinus longimanus",
              "Histrio histrio",
              "Istiophorus platypterus",
              "Sphyrna lewini",
              "Elasmobranchii spp.",
              "Katsuwonus pelamis",
              "Scomberomorus spp.",
              "Xiphiidae spp.",
              "Opisthonema spp.",
              "Scombridae",
              "Exocoetidae spp.",
              "Elasmobranch",
              "Osteichthyes spp.",
              "Rajiformes spp.",
              "Osteichthyes spp.",
              "Dasyatidae spp.",
              "--",
              "Acanthocybium solandri",
              "Kajikia albida",
              "Thunnus albacares",
              "--",
              "--",
              "--",
              "--",
              "Pachydiplax longipennis",
              "Papilio polyxenes ",
              "--",
              "--",
              "--",
              "--",
              "--",
              "--",
              "--",
              "--",
              "--",
              "--", 
              "--",
              "--",
              "--",
              "--",
              "--",
              "--",
              "--",
              "--",
              "--",
              "--", 
              "--",
              "--",
              "--",
              "--",
              "Papilio polyxenes",
              "--",
              "--",
              "Stomolophus meleagris",
              "--",
              "Phoebis sennae",
              "--",
              "--",
              "--",
              "--",
              "--",
              "--",
              "--",
              "--",
              "Papilio cresphontes",
              "Anax junius",
              "Limulus polyphemus",
              "--",
              "--",
              "--",
              "--",
              "--",
              "Danaus plexippus",
              "Aurelia aurita",
              "--",
              "--",
              "--",
              "Colias eurytheme",
              "--",
              "Vanessa cardui",
              "Physalia physalis",
              "Ursus maritimus",
              "--",
              "Pilea microphylla",
              "Lasiurus borealis",
              "--",
              "--",
              "Coliadinae spp.",
              "Epiaeschna heros",
              "--",
              "--",
              "--",
              "--",
              "--",
              "--",
              "Scyphozoa spp.",
              "--",
              "--",
              "Pantala flavescens",
              "--",
              "Chelonia mydas",
              "Eretmochelys imbricata",
              "Lepidochelys kempii",
              "Dermochelys coriacea",
              "Caretta caretta",
              "--",
              "--",
              "Cheloniidae spp."),
            c("--","175068","174856","176292","179731","179236","176564",
              "175622","176472","554127", "178979", "179759", "175094",
            "176580","174755",      "--", "174471", "176890", "177025", 
            "179432", "174561", "174684", "175420", "175144", "177851", 
            "178436", "179083", "177921", "178448", "176655", "178844", 
            "177834", "176567", "174655", "178250", "554382", "174832", 
            "174567", "178106", "174568", "174516", "179853", "179112", 
            "176835", "178904", "176985", "179680", "176875", "176944", 
            "176475", "178913", "175171", "554447", "174640", "176959", 
            "175272", "176726", "179032", "554386", "176839", "178529", 
            "175011", "179094", "174704", "178803", "176941", "174685", 
            "174636", "176897", "178627", "178888", "179108", "176831", 
            "178898", "175145", "554144", "175349", "554396", "175086", 
            "178853", "177013", "554383", "174803", "176829", "174999", 
            "175129", "178581", "178460", "176924", "950079", "178532",
            "176445",     "--", "179435", "178001", "176209", "178455", 
            "178887", "175155", "708108", "175141", "179104", "175309", 
            "174469", "175185", "176284", "176974", "177979", "554395", 
            "179725", "179230", "203446", "176700", "176888", "178944", 
            "723253",     "--", "174717", "179410", "176982", "176674", 
            "178259", "176661", "179801", "178279", "179034", "178329", 
            "686658", "179276",     "--", "176469", "174663", "179637", 
            "175092", "179173", "175598", "562557", "174548", "179737", 
            "179443", "179464", "176887", "176838", "174625", "175073", 
            "176815", "174773",     "--", "176926", "179865",     "--", 
            "177884", "176808", "174924",     "--", "179667", "178280", 
            "178625", "174715", "554135", "174766", "174793", "175130", 
            "174549", "660059", "179333", "176619", "--",     "175020",
            "176814", "175081", "175149", "562561",     "--", "178262", 
            "174570", "176824", "179779", "179191", "174482", "554256", 
            "175183", "179231", "179628", "178972", "178541", "176690", 
            "176811", "179150", "176851", "174575", "179409", "175160", 
            "176520", "176207", "176813", "176837", "179526", "176821", 
            "176679", "174827", "174646", "176943", "177932", "176656", 
            "175134", "174628", "176923", "176620", "176840", "174559", 
            "179484", "824124", "179524", "178515", "175038", "175038", 
            "175147", "176794", "174699", "174763", "176686", "175063", 
            "174555", "178886", "178608", "179033", "176832", "175613", 
            "177125", "176522", "178939", "174985", "178892", "178861", 
            "177898", "175863", "179124", "178154", "174536", "174712", 
            "175300", "175430", "178620", "178868", "175074",     "--",
            "178931", "178443", "175096", "178511", "554031", "177942", 
            "178856", "179064", "175590", "178927", "176793", "174475", 
            "178921", "174505", "174725",     "--", "175604",     "--", 
            "176653", "174547",     "--", "179205",     "--", "179233", 
            "178914", "178166", "176792", "174661", "178918", "178846", 
            "179186", "178464", "176646", "176971", "179139", "176830", 
            "175187", "178784", "174673", "178195", "179870", "179259", 
            "175125",     "--", "174824", "176642", "554376", "179021", 
            "174707", "177023", "178186", "177136", "175373", "175128", 
            "175905", "174479", "176735", "177071", "174941", "176891", 
            "178439", "176922", "175359", "175350", "178032", "174474", 
            "174679", "179091", "175175", "175790", "176571", "179045", 
            "176177", "176866", "176669", "176927", "179314", "176675",
            "176816",    "--" ,     "--", "179883", "177935", "176506", 
            "176667", "178605", "174733",     "--", "179532", "174813", 
            "175038", "686683", "176854", "176242", "176615", "174553", 
            "179492", "176894", "178838", "175161", "553896", "176994", 
            "178499", "176612", "660062", "175304", "175153", "554145", 
            "174554", "175170", "178423", "174993", "174642", "179488", 
            "562522", "176978", "178855", "176828", "174558", "178431",     
            "--",     "174641", "177032", "174987", "554138", "175265", 
            "175299", "174513",     "--",     "--",     "--",     "--",     
            "--",     "174982",     "--", "176984",     "--",     "--", 
            "176967", "179332", "174371", "179030", "174697",     "--",     
            "174714", "179724", "175124",     "--",     "--", "175154", 
            "179225", "178337", "174762", "175140", "175140", "174478", 
            "--",         "--",     "--", "176791",     "--",     "--", 
            "174468", "176205",     "--",     "--",     "--",     "--", 
            "176973",     "--",     "--", "179063", "177854",     "--", 
            "174532", "176733", "174532", "174566", "177024",     "--",     
            "--",     "175162",     "--", "174532", "176791",     "--",     
            "--",     "176885", "174696",     "--", "174672", "176885", 
            "179751",     "--",     "--",     "--",     "--",     "--", 
            "176568",     "--",     "--", "178851", "179366", "176221",
            "178489", "178775", "174656", "179455", "176914", "176817", 
            "176668", "178991", "174621", "174930", "176599", "176954", 
            "176638", "176736", "176517", "726048", "174650", "176136", 
            "178973", "178547", "175122", "179777", "176654", "174638", 
            "174550", "179462", "174676", "176958", "179268", "177121", 
            "--",     "175163", "177011", "178964", "177831", "178338", 
            "178202", "174842", "562599", "179043", "554270", "554452", 
            "178891", "178878", "552460",     "--", "180655", "180528", 
            "180426",     "--", "180498", "180435", "180438", "180490", 
            "180492", "180527", "180463", "180440",     "--", "180653", 
            "180473", "180649", "180657", "622022", "180530", "180469", 
            "552461", "180429", "180459", "180524", "180504", "180464", 
            "180460", "180430", "180491", "180457", "622018", "180537", 
            "180417", "180515", "180526", "180466", "180428", "180489", 
            "180434",     "--", "180506", "552298", "180437", "180403", 
            "180415",     "--",     "--",     "--", "180403", "179913",     
            "--",     "180522", "180640", "180403", "180404", "180403", 
            "180493", "180640", "180639", "180442", "180684", "180443",
            "172419", "159907", "172421", "172486", "172427", "172491", 
            "160424", "168559", "172398", "160985", "172402", "161030", 
            "160992", "159903", "160497", "172435", "159923", "168791", 
            "160990", "173414", "160330", "164520", "172488", "160508", 
            "159786", "172401", "172434", "172480", "161747", "172398", 
            "165431",     "--", "161030", "160806", "161030",     "--",     
            "--", "    172451", "768126", "172423",     "--",     "--",     
            "--",         "--", "101799", "188545",     "--",     "--",     
            "--",         "--",     "--",     "--",     "--",     "--",     
            "--",         "--",     "--",     "--",     "--",     "--",     
            "--",         "--",     "--",     "--",     "--",     "--",         
            "--",         "--",     "--",     "--", "188543",     "--",     
            "--",      "51926",     "--", "777750",     "--",     "--",  
            "--",         "--",     "--",     "--",     "--",     "--",     
            "--",     "101598",  "82703",     "--",     "--",     "--",     
            "--",         "--", "117273",  "51701",     "--",     "--",     
            "--",     "188528",     "--", "188601", "719181", "180542",     
            "--",      "19133", "180016",  "11389",     "--", "694016", 
            "101638",     "--",     "--",     "--",     "--",     "--",     
            "--",      "51483",     "--",     "--", "101801",     "--", 
            "173833", "173837", "551770", "173843", "173830",     "--",     
            "--",     "--"))

spp = as.data.frame(spp)
colnames(spp) = c("Code Type","Species Code","Common Name","Scientific Name","ITIS Code")
```

```{r kable, results = 'asis'}
kable(spp)
```
